"""Add Tanent Link

Revision ID: 0462ac208c05
Revises: 90fa1c503036
Create Date: 2025-12-27 17:26:07.396433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0462ac208c05'
down_revision: Union[str, None] = '90fa1c503036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['auth_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_links_tenant_id'), 'tenant_links', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_links_token_hash'), 'tenant_links', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_links_token_hash'), table_name='tenant_links')
    op.drop_index(op.f('ix_tenant_links_tenant_id'), table_name='tenant_links')
    op.drop_table('tenant_links')
    # ### end Alembic commands ###
