"""Added fields to OAuthClient

Revision ID: 053abe8911e8
Revises: ebcd6ef79447
Create Date: 2025-02-07 07:00:45.640620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053abe8911e8'
down_revision: Union[str, None] = 'ebcd6ef79447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('name', sa.String(), nullable=False))
    op.add_column('oauth_clients', sa.Column('hash_client_secret', sa.String(), nullable=True))
    op.add_column('oauth_clients', sa.Column('client_type', sa.String(), nullable=False))
    op.add_column('oauth_clients', sa.Column('authorization_grant_type', sa.String(), nullable=False))
    op.add_column('oauth_clients', sa.Column('redirect_uris', sa.String(), nullable=True))
    op.add_column('oauth_clients', sa.Column('post_logout_redirect_uris', sa.String(), nullable=True))
    op.add_column('oauth_clients', sa.Column('allowed_origins', sa.String(), nullable=True))
    op.add_column('oauth_clients', sa.Column('algorithm', sa.String(), nullable=False))
    op.add_column('oauth_clients', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('oauth_clients', 'client_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('oauth_clients', 'redirect_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('redirect_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('oauth_clients', 'client_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('oauth_clients', 'created_at')
    op.drop_column('oauth_clients', 'algorithm')
    op.drop_column('oauth_clients', 'allowed_origins')
    op.drop_column('oauth_clients', 'post_logout_redirect_uris')
    op.drop_column('oauth_clients', 'redirect_uris')
    op.drop_column('oauth_clients', 'authorization_grant_type')
    op.drop_column('oauth_clients', 'client_type')
    op.drop_column('oauth_clients', 'hash_client_secret')
    op.drop_column('oauth_clients', 'name')
    # ### end Alembic commands ###
