"""Add Payment tables

Revision ID: 0ac8eff97183
Revises: 8d53b34bb8fb
Create Date: 2026-01-09 18:32:41.804109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac8eff97183'
down_revision: Union[str, None] = '8d53b34bb8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_details', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'payment_details')
    # ### end Alembic commands ###
