"""add new colomn in oauth client

Revision ID: 16a05823eb25
Revises: 4bc344c0f508
Create Date: 2025-02-18 21:31:47.933767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a05823eb25'
down_revision: Union[str, None] = '4bc344c0f508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('skip_authorization', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_clients', 'skip_authorization')
    # ### end Alembic commands ###
