"""Add Plan Version

Revision ID: 3a80bb9ebb40
Revises: c9f9d55536f8
Create Date: 2025-12-31 00:32:40.861024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a80bb9ebb40'
down_revision: Union[str, None] = 'c9f9d55536f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
