"""update

Revision ID: 3b2e99300901
Revises: 915054b2048c
Create Date: 2026-01-10 23:33:43.794148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2e99300901'
down_revision: Union[str, None] = '915054b2048c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_tenant_uuid_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'tenant_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tenant_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('subscriptions_tenant_uuid_fkey', 'subscriptions', 'tenants', ['tenant_uuid'], ['tenant_uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
