"""Initial migration

Revision ID: 5fcdd362f845
Revises: eb0c60a6697c
Create Date: 2025-02-18 20:24:07.835695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fcdd362f845'
down_revision: Union[str, None] = 'eb0c60a6697c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('redirect_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('oauth_clients', sa.Column('post_logout_redirect_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('oauth_clients', 'post_logout_redirect_uris')
    op.drop_column('oauth_clients', 'redirect_uris')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('redirect_uris', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('oauth_clients', sa.Column('post_logout_redirect_uris', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('oauth_clients', 'post_logout_redirect_urls')
    op.drop_column('oauth_clients', 'redirect_urls')
    # ### end Alembic commands ###
