"""update

Revision ID: 617a29dc14bd
Revises: 0ac8eff97183
Create Date: 2026-01-10 22:27:10.176291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617a29dc14bd'
down_revision: Union[str, None] = '0ac8eff97183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan_code', sa.String(length=50), nullable=True))
    op.add_column('tenant_subscription_apps', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tenant_subscription_apps', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('tenant_subscription_apps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tenant_subscription_apps', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_subscription_features', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tenant_subscription_features', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('tenant_subscription_features', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tenant_subscription_features', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_subscription_features', 'updated_at')
    op.drop_column('tenant_subscription_features', 'created_at')
    op.drop_column('tenant_subscription_features', 'status')
    op.drop_column('tenant_subscription_features', 'is_active')
    op.drop_column('tenant_subscription_apps', 'updated_at')
    op.drop_column('tenant_subscription_apps', 'created_at')
    op.drop_column('tenant_subscription_apps', 'status')
    op.drop_column('tenant_subscription_apps', 'is_active')
    op.drop_column('subscriptions', 'plan_code')
    # ### end Alembic commands ###
