"""Update Permission model for multiple scopes

Revision ID: 8bdbff8bd9d5
Revises: dace5005ee49
Create Date: 2025-03-16 16:42:41.528730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bdbff8bd9d5'
down_revision: Union[str, None] = 'dace5005ee49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_permissions', sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('auth_permissions', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_permissions', sa.Column('scope', postgresql.ENUM('read', 'write', 'edit', 'delete', name='scopeenum'), autoincrement=False, nullable=False))
    op.drop_column('auth_permissions', 'scopes')
    # ### end Alembic commands ###
