"""Add New key in OauthClient

Revision ID: 90a0e4697547
Revises: 96966cc63da5
Create Date: 2025-03-19 21:06:49.832983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a0e4697547'
down_revision: Union[str, None] = '96966cc63da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_clients', 'updated_at')
    # ### end Alembic commands ###
