"""add uuid in plan and scubscription 

Revision ID: 90fa1c503036
Revises: 5b642498da6d
Create Date: 2025-12-27 16:18:32.194672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fa1c503036'
down_revision: Union[str, None] = '5b642498da6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saas_plans', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'saas_plans', ['uuid'])
    op.add_column('saas_subscriptions', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'saas_subscriptions', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saas_subscriptions', type_='unique')
    op.drop_column('saas_subscriptions', 'uuid')
    op.drop_constraint(None, 'saas_plans', type_='unique')
    op.drop_column('saas_plans', 'uuid')
    # ### end Alembic commands ###
