"""update

Revision ID: 915054b2048c
Revises: 9f01b238c80e
Create Date: 2026-01-10 23:28:03.436616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915054b2048c'
down_revision: Union[str, None] = '9f01b238c80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tenant_uuid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant_uuid'], ['tenant_uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'tenant_uuid')
    # ### end Alembic commands ###
