"""add Description ROle

Revision ID: 96966cc63da5
Revises: 8bdbff8bd9d5
Create Date: 2025-03-18 21:58:14.405248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96966cc63da5'
down_revision: Union[str, None] = '8bdbff8bd9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_roles', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_roles', 'description')
    # ### end Alembic commands ###
