"""update

Revision ID: 9f01b238c80e
Revises: 617a29dc14bd
Create Date: 2026-01-10 22:50:57.489391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9f01b238c80e'
down_revision: Union[str, None] = '617a29dc14bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('plan_version_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'grace', 'expired', 'cancelled', name='subscriptionstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_version_id'], ['saas_plan_versions.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('subscriptions_plan_version_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'plan_code')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'plan_version_id')
    op.drop_column('subscriptions', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('plan_version_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('plan_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('subscriptions_plan_version_id_fkey', 'subscriptions', 'saas_plan_versions', ['plan_version_id'], ['id'])
    op.drop_table('subscription_cycles')
    # ### end Alembic commands ###
