"""Added fields to OAuthClient

Revision ID: a63a5dc2f7f6
Revises: d77cac94ef2e
Create Date: 2025-02-07 08:11:51.971417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63a5dc2f7f6'
down_revision: Union[str, None] = 'd77cac94ef2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('redirect_urls', sa.String(), nullable=True))
    op.drop_column('oauth_clients', 'redirect_uris')
    op.drop_column('oauth_clients', 'hash_client_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('hash_client_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('oauth_clients', sa.Column('redirect_uris', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('oauth_clients', 'redirect_urls')
    # ### end Alembic commands ###
