"""update

Revision ID: d77e6bb66322
Revises: 619d576f9043
Create Date: 2026-01-11 11:41:32.340723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77e6bb66322'
down_revision: Union[str, None] = '619d576f9043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tenant_link_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'tenant_links', ['tenant_link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'tenant_link_id')
    # ### end Alembic commands ###
