"""Add scope to Permission model

Revision ID: dace5005ee49
Revises: 2c61c6a6c4a3
Create Date: 2025-03-16 15:14:14.368618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dace5005ee49'
down_revision: Union[str, None] = '2c61c6a6c4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['auth_tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_roles_id'), 'auth_roles', ['id'], unique=False)
    op.create_table('auth_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('read', 'write', 'edit', 'delete', name='scopeenum'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_permissions_id'), 'auth_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_permissions_id'), table_name='auth_permissions')
    op.drop_table('auth_permissions')
    op.drop_index(op.f('ix_auth_roles_id'), table_name='auth_roles')
    op.drop_table('auth_roles')
    # ### end Alembic commands ###
