"""auth_tanet

Revision ID: ebcd6ef79447
Revises: ffae7388119a
Create Date: 2025-02-06 20:59:19.556500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcd6ef79447'
down_revision: Union[str, None] = 'ffae7388119a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_email', sa.String(), nullable=False),
    sa.Column('tenant_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_email'),
    sa.UniqueConstraint('tenant_id'),
    sa.UniqueConstraint('tenant_name')
    )
    op.create_index(op.f('ix_auth_tenants_id'), 'auth_tenants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_tenants_id'), table_name='auth_tenants')
    op.drop_table('auth_tenants')
    # ### end Alembic commands ###
