"""Init

Revision ID: f1a06b7cbd1d
Revises: ea04427cbda2
Create Date: 2026-01-04 19:10:56.928814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a06b7cbd1d'
down_revision: Union[str, None] = 'ea04427cbda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saas_plan_versions', sa.Column('max_users', sa.Integer(), nullable=True))
    op.add_column('saas_plan_versions', sa.Column('max_branches', sa.Integer(), nullable=True))
    op.add_column('saas_plan_versions', sa.Column('storage_limit_gb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saas_plan_versions', 'storage_limit_gb')
    op.drop_column('saas_plan_versions', 'max_branches')
    op.drop_column('saas_plan_versions', 'max_users')
    # ### end Alembic commands ###
