"""update

Revision ID: fbb166f6012f
Revises: 3b2e99300901
Create Date: 2026-01-11 01:21:27.879507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb166f6012f'
down_revision: Union[str, None] = '3b2e99300901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('auth_users', sa.Column('is_root_user', sa.Boolean(), nullable=True))
    op.add_column('auth_users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.alter_column('auth_users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('auth_users', 'is_superuser')
    op.drop_column('auth_users', 'is_root_user')
    op.drop_column('auth_users', 'is_active')
    # ### end Alembic commands ###
